/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import cacd.Cacd;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author RR
 */
public class Evidence extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    File selectedFile;
    File selectedFile2;
    int flag;
    
    /**
     * Creates new form evidence
     */
    public Evidence() {
        initComponents();
        conn = Cacd.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        evidenceID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EvidenceType = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EvidenceDetails = new javax.swing.JTextField();
        retrieve = new javax.swing.JButton();
        update = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CaseID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        suspectID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        victimRelation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        retrieve2 = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        age = new javax.swing.JSpinner();
        height = new javax.swing.JSpinner();
        weight = new javax.swing.JSpinner();
        add2 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        labelfp = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        caseid = new javax.swing.JTextField();
        addFingerPrint = new javax.swing.JButton();
        addImage = new javax.swing.JButton();
        convicted = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        radioB_male = new javax.swing.JRadioButton();
        radioB_fmale = new javax.swing.JRadioButton();
        radioB_other = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        eyecolor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 770));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Evidence and Suspects");

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setText("x");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 191));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Evidence ID");

        evidenceID.setColumns(10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Evidence Type");

        EvidenceType.setColumns(10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Evidence Details");

        EvidenceDetails.setColumns(10);
        EvidenceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvidenceDetailsActionPerformed(evt);
            }
        });

        retrieve.setBackground(new java.awt.Color(51, 102, 255));
        retrieve.setForeground(new java.awt.Color(255, 255, 255));
        retrieve.setText("Retrieve");
        retrieve.setBorderPainted(false);
        retrieve.setContentAreaFilled(false);
        retrieve.setOpaque(true);
        retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieveActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(51, 102, 255));
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.setBorderPainted(false);
        update.setContentAreaFilled(false);
        update.setOpaque(true);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(51, 102, 255));
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setOpaque(true);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(51, 102, 255));
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setOpaque(true);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Case ID");

        CaseID.setColumns(10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EvidenceType, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(evidenceID, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(retrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(EvidenceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(CaseID)
                        .addGap(164, 164, 164)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(evidenceID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(EvidenceType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(EvidenceDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Evidence");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Suspects");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 102, 255)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Suspect ID");

        suspectID.setColumns(10);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name");

        victimRelation.setColumns(10);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Age");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Height");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Relation to the deceased");

        retrieve2.setBackground(new java.awt.Color(51, 102, 255));
        retrieve2.setForeground(new java.awt.Color(255, 255, 255));
        retrieve2.setText("Retrive");
        retrieve2.setBorderPainted(false);
        retrieve2.setContentAreaFilled(false);
        retrieve2.setOpaque(true);
        retrieve2.setPreferredSize(new java.awt.Dimension(100, 32));
        retrieve2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrieve2ActionPerformed(evt);
            }
        });

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        name.setColumns(10);
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Fingerprint");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Weight");

        add2.setBackground(new java.awt.Color(51, 102, 255));
        add2.setForeground(new java.awt.Color(255, 255, 255));
        add2.setText("Add");
        add2.setBorderPainted(false);
        add2.setContentAreaFilled(false);
        add2.setOpaque(true);
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        delete2.setBackground(new java.awt.Color(51, 102, 255));
        delete2.setForeground(new java.awt.Color(255, 255, 255));
        delete2.setText("Delete");
        delete2.setBorderPainted(false);
        delete2.setContentAreaFilled(false);
        delete2.setOpaque(true);
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        labelfp.setBackground(new java.awt.Color(255, 255, 255));
        labelfp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Case ID");

        caseid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseidActionPerformed(evt);
            }
        });

        addFingerPrint.setBackground(new java.awt.Color(51, 102, 255));
        addFingerPrint.setForeground(new java.awt.Color(255, 255, 255));
        addFingerPrint.setText("+");
        addFingerPrint.setBorderPainted(false);
        addFingerPrint.setContentAreaFilled(false);
        addFingerPrint.setOpaque(true);
        addFingerPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFingerPrintActionPerformed(evt);
            }
        });

        addImage.setBackground(new java.awt.Color(51, 102, 255));
        addImage.setForeground(new java.awt.Color(255, 255, 255));
        addImage.setText("+");
        addImage.setBorderPainted(false);
        addImage.setContentAreaFilled(false);
        addImage.setOpaque(true);
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });

        convicted.setBackground(new java.awt.Color(51, 102, 255));
        convicted.setForeground(new java.awt.Color(255, 255, 255));
        convicted.setText("Convicted");
        convicted.setBorderPainted(false);
        convicted.setContentAreaFilled(false);
        convicted.setOpaque(true);
        convicted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convictedActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender");

        radioB_male.setText("Male");

        radioB_fmale.setText("Female");

        radioB_other.setText("Others");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Eye Color");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(radioB_male)))
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel7))
                                        .addGap(14, 14, 14))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(labelfp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(retrieve2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(addFingerPrint)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(suspectID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                                        .addComponent(jLabel18)
                                        .addGap(53, 53, 53))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(victimRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(radioB_fmale)
                                                .addGap(18, 18, 18)
                                                .addComponent(radioB_other))
                                            .addComponent(eyecolor))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addGap(9, 9, 9)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(279, 279, 279)
                                .addComponent(addImage, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(caseid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(convicted)
                                .addGap(67, 67, 67))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(322, 322, 322)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addImage)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16)))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(suspectID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(caseid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(victimRelation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel4)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(radioB_male)
                                    .addComponent(radioB_fmale)
                                    .addComponent(radioB_other))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eyecolor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(convicted, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(weight, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(retrieve2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addComponent(labelfp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addFingerPrint))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 536, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1701, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EvidenceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvidenceDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EvidenceDetailsActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Case nf = new Case();
        nf.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void retrieve2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieve2ActionPerformed
        // TODO add your handling code here:
        try{
            pst=conn.prepareStatement("select * from suspect,suspect_details where sid = ? and sid = suspectID");
            pst.setString(1,suspectID.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                name.setText(rs.getString("name"));
                caseid.setText(rs.getString("caseid"));
                victimRelation.setText(rs.getString("victimRelation"));
                age.setValue(rs.getInt("age"));
                height.setValue(rs.getInt("height"));
                weight.setValue(rs.getInt("weight"));
                eyecolor.setText(rs.getString("eye_color"));
                
                if(rs.getString("gender").equals("M"))
                   radioB_male.setSelected(true);
                else if(rs.getString("gender").equals("F"))
                   radioB_fmale.setSelected(true);
                else
                   radioB_other.setSelected(true);
                
                String imagefpURL = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_FingerImages" + "/" + rs.getString("sid") + ".jpg";
                labelfp.setIcon(resizeImagefp(imagefpURL));
                
                String imageURL = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_Images" + "/" + rs.getString("sid") + ".jpg";
                label.setIcon(resizeImage(imageURL));
            }
            else{
                JOptionPane.showMessageDialog(null, "The record does not exist");
                suspectID.setText("");
                name.setText("");
                caseid.setText("");
                victimRelation.setText("");
                age.setValue(0);
                height.setValue(0);
                weight.setValue(0);
                label.setIcon(null);
                labelfp.setIcon(null);
            }
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_retrieve2ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
        try{
            
            pst=conn.prepareStatement("insert into suspect(sid,caseid,name,victimRelation,status) values (?,?,?,?,?)");
            pst.setString(1,suspectID.getText());
            pst.setString(2,caseid.getText());
            pst.setString(3,name.getText());
            pst.setString(4,victimRelation.getText());
            pst.setString(5,"Not Convicted");
            pst.executeUpdate();
            
            pst=conn.prepareStatement("insert into suspect_details (suspectID,age,gender,eye_color,height,weight) values (?,?,?,?,?,?)");
            pst.setString(1,suspectID.getText());
            pst.setInt(2, (int) age.getValue());
            if(radioB_male.isSelected())
                pst.setString(3,"M");
            else if(radioB_fmale.isSelected())
                pst.setString(3,"F");
            else
                 pst.setString(3,"O");
            pst.setString(4,eyecolor.getText());
            pst.setInt(5, (int) height.getValue());
            pst.setInt(6, (int) weight.getValue());
            
            int rs = pst.executeUpdate();
            
            try{

            BufferedImage img=ImageIO.read(selectedFile);
            BufferedImage imgfp = ImageIO.read(selectedFile2);
            String locationfp = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_FingerImages/" + suspectID.getText() + ".jpg";
            String formatfp = "jpg";
            String location = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_Images/" + suspectID.getText() + ".jpg";
            String format = "jpg";
            ImageIO.write(imgfp, formatfp, new File(locationfp));
            ImageIO.write(img, format, new File(location));
            
            }
            catch(IOException e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            
            if(rs!=0){ 
                 
                    JOptionPane.showMessageDialog(null, "New Record Inserted!"); 
                 
            }
            else{
                 JOptionPane.showMessageDialog(null, "Please enter valid records and try again");     
            }
            
        }catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_add2ActionPerformed

    private void retrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrieveActionPerformed
        // TODO add your handling code here:
        
        try{
            
            pst=conn.prepareStatement("select * from evidence where eid = ? ");
            pst.setString(1,evidenceID.getText());
            
            rs=pst.executeQuery();
            
            if(rs.next())
            {
                EvidenceType.setText(rs.getString("evidenceType"));
                CaseID.setText(rs.getString("caseid"));
                EvidenceDetails.setText(rs.getString("evidenceDetails"));
            }
            else{
                JOptionPane.showMessageDialog(null, "The record does not exist");
                
                evidenceID.setText("");
                EvidenceType.setText("");
                CaseID.setText("");
                EvidenceDetails.setText("");
            }
            
        }catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_retrieveActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try
        {
            pst=conn.prepareStatement("insert into evidence(eid,caseid,evidenceType,evidenceDetails) values (?,?,?,?)");
            pst.setString(1,evidenceID.getText());
            pst.setString(2,CaseID.getText());
            pst.setString(3,EvidenceType.getText());
            pst.setString(4,EvidenceDetails.getText());
            
            flag = pst.executeUpdate();
            
            if(flag!=0){ 
                 
                    JOptionPane.showMessageDialog(null, "New Record Inserted!"); 
                 
            }
            else{
                 JOptionPane.showMessageDialog(null, "Please enter valid records and try again");     
            }
            
        }catch(HeadlessException | SQLException e)
        {
            
        }
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            //pst = conn.prepareStatement("PRAGMA foreign_keys=ON");
            //pst.execute();
            int p=JOptionPane.showConfirmDialog(null,"Are u sure u want to delete?","delete",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
            pst = conn.prepareStatement("delete from evidence where eid = ?");
            pst.setString(1,evidenceID.getText());
            
            flag = pst.executeUpdate();
            
            if(flag != 0)
            {
                JOptionPane.showMessageDialog(null, "Deletion Successful");
                
                evidenceID.setText("");
                EvidenceType.setText("");
                CaseID.setText("");
                EvidenceDetails.setText("");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The record does not exist");
            }
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
        try{   
            pst=conn.prepareStatement("UPDATE evidence set caseid = ?, evidenceType = ?, evidenceDetails = ? WHERE eid = ?");
            pst.setString(1,CaseID.getText());
            pst.setString(2,EvidenceType.getText());
            pst.setString(3,EvidenceDetails.getText());
            pst.setString(4,evidenceID.getText());
            
            flag = pst.executeUpdate();
            
            if(flag != 0)
            {
                JOptionPane.showMessageDialog(null, "Updation Successful!");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "The record does not exist");
            }
            
        }catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void caseidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseidActionPerformed

    private void addFingerPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFingerPrintActionPerformed
        // TODO add your handling code here:
        
        JFileChooser file = new JFileChooser("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd");
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
            selectedFile2 = file.getSelectedFile();
            String path = selectedFile2.getAbsolutePath();
            labelfp.setIcon(resizeImagefp(path));
        }
        else if(result == JFileChooser.CANCEL_OPTION)
        {
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_addFingerPrintActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd");
        //file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        
        if(result == JFileChooser.APPROVE_OPTION)
        {
            selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            label.setIcon(resizeImage(path));
        }
        else if(result == JFileChooser.CANCEL_OPTION)
        {
            System.out.println("No file selected");
        }
    }//GEN-LAST:event_addImageActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        try{
            //pst = conn.prepareStatement("PRAGMA foreign_keys=ON");
            //pst.execute();
            int p=JOptionPane.showConfirmDialog(null,"Are u sure u want to delete?","delete",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
            pst = conn.prepareStatement("delete from suspect where sid = ?");
            pst.setString(1,suspectID.getText());
            
            flag = pst.executeUpdate();
            
            if(flag == 0)
            {
                JOptionPane.showMessageDialog(null, "The record does not exist");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Deletion Successful");
            }
            
            suspectID.setText("");
            name.setText("");
            victimRelation.setText("");
            caseid.setText("");
            age.setValue(0);
            height.setValue(0);
            weight.setValue(0);
            eyecolor.setText("");
            radioB_male.setSelected(false);
            radioB_fmale.setSelected(false);
            radioB_other.setSelected(false);
            
            label.setIcon(null);
            labelfp.setIcon(null);
            
            try{
    		
                    File file = new File("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_Images" + "/" + rs.getString("sid") + ".jpg");
                    File filefp = new File("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_FingerImages" + "/" + rs.getString("sid") + ".jpg");
                    
                    if(file.delete()){
                        System.out.println(file.getName() + " is deleted!");
                    }
                    else{
    			System.out.println("Delete operation is failed.");
                    }
                    
                    if(filefp.delete()){
                        System.out.println(file.getName() + " is deleted!");
                    }
                    else{
    			System.out.println("Delete operation is failed.");
                    }
    	   
                }catch(Exception e){
    		
    		JOptionPane.showMessageDialog(null, e);
    		
    	}
            } 
        }catch(Exception e){
    		
    		JOptionPane.showMessageDialog(null, e);
    		
    	}
        
        
    }//GEN-LAST:event_delete2ActionPerformed

    private void convictedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convictedActionPerformed
        // TODO add your handling code here
        try{
            
            int p=JOptionPane.showConfirmDialog(null,"Are u sure u want to update?","delete",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
                try{
                    
                pst=conn.prepareStatement("update suspect set status = 'convicted' where sid = ?");
                pst.setString(1,suspectID.getText());
            
                pst.executeUpdate();
                
                File source = new File("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_Images" + "/" + suspectID.getText()+ ".jpg");
                File sourcefp = new File("C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Suspect_FingerImages" + "/" + suspectID.getText() + ".jpg");
                BufferedImage img=ImageIO.read(source);
                BufferedImage imgfp=ImageIO.read(sourcefp);
                pst=conn.prepareStatement("select criminal_id from criminal order by criminal_id desc limit 1");
                rs = pst.executeQuery();
                if(rs.next())
                {
                String location = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/Criminal_Images/" + rs.getInt("criminal_id") + ".jpg";
                String locationfp = "C:/Users/Shivesh Srivastava/Documents/NetBeansProjects/cacd/FingerPrint_Images/" + rs.getInt("criminal_id") + ".jpg";
                String format = "jpg";
                ImageIO.write(img, format, new File(location));
                ImageIO.write(imgfp, format, new File(locationfp));
                }
                }
                catch(HeadlessException | SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            
    }//GEN-LAST:event_convictedActionPerformed

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isAlphabetic(c)))
            evt.consume();
    }//GEN-LAST:event_nameKeyTyped

    
    public ImageIcon resizeImagefp(String imagePath)
    {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(labelfp.getWidth(), labelfp.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    public ImageIcon resizeImage(String imagePath)
    {
        ImageIcon myImage = new ImageIcon(imagePath);
        Image img = myImage.getImage();
        Image newImage = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evidence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Evidence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaseID;
    private javax.swing.JTextField EvidenceDetails;
    private javax.swing.JTextField EvidenceType;
    private javax.swing.JButton add;
    private javax.swing.JButton add2;
    private javax.swing.JButton addFingerPrint;
    private javax.swing.JButton addImage;
    private javax.swing.JSpinner age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField caseid;
    private javax.swing.JButton convicted;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete2;
    private javax.swing.JTextField evidenceID;
    private javax.swing.JTextField eyecolor;
    private javax.swing.JSpinner height;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelfp;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton radioB_fmale;
    private javax.swing.JRadioButton radioB_male;
    private javax.swing.JRadioButton radioB_other;
    private javax.swing.JButton retrieve;
    private javax.swing.JButton retrieve2;
    private javax.swing.JTextField suspectID;
    private javax.swing.JButton update;
    private javax.swing.JTextField victimRelation;
    private javax.swing.JSpinner weight;
    // End of variables declaration//GEN-END:variables
}
